spring:
  jpa:
    database: "POSTGRESQL"
    show-sql: "true"
    properties:
      hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"
  database:
    driverClassName: "org.postgresql.Driver"
  datasource:
    platform: "postgres"
    url: "jdbc:postgresql://PGSERVER:5432/eagle_eye_local"
    username: "postgres"
    password: "abc123"
    testWhileIdle: "true"
    validationQuery: "SELECT 1"

server:
  port: 6010
  
signing:
  key: "345345fsdfsf5345"
