example:
    property: "I AM IN THE DEFAULT"
spring:
  jpa:
    database: "POSTGRESQL"
    show-sql: "true"
    properties:
      hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"
  database:
    driverClassName: "org.postgresql.Driver"
  datasource:
    platform: "postgres"
    url: "jdbc:postgresql://PGSERVER:5432/eagle_eye_local"
    username: "postgres"
    password: "abc123"
    testWhileIdle: "true"
    validationQuery: "SELECT 1"

server:
  port: 6020
  
redis:
    server: "redis"
    port: 6379
signing.key: "345345fsdfsf5345"
